import React from 'react'
import Metrics from './Metrics'
import InteractiveCharts from './InteractiveCharts'
import RiskCalculator from './RiskCalculator'

const Analysis = () => {
  return (
    <section id="analysis" className="px-6 py-12 bg-white">
      <div className="max-w-4xl mx-auto">
        <h2 className="text-2xl font-semibold mb-4">
          Analysis & Insight Report
        </h2>

        <p className="mb-4">
          This page shows a concise insight report exported from the analysis
          notebook. Replace the placeholder files with the real outputs from
          running the Colab notebook.
        </p>

        {/* Summary Chart */}
        <div className="mb-6">
          <img
            src="/assets/images/summary_chart.svg"
            alt="Summary chart"
            className="w-full rounded-md shadow-sm"
          />
        </div>

        {/* Action Buttons */}
        <div className="mb-6">
          <a
            href="https://colab.research.google.com/drive/1jACyeDgfPhRlNVxUDrIUNJ3CjBuP4qRb?usp=sharing"
            target="_blank"
            rel="noreferrer"
            className="inline-block bg-indigo-600 text-white px-4 py-2 rounded-md shadow hover:bg-indigo-500"
          >
            Open Notebook in Colab
          </a>

          <a
            href="/insight_report.html"
            target="_blank"
            rel="noreferrer"
            className="inline-block ml-3 bg-blue-600 text-white px-4 py-2 rounded-md shadow hover:bg-blue-500"
          >
            Open Insight Report
          </a>

          <a
            href="/assets/images/summary_chart.svg"
            download
            className="inline-block ml-3 bg-gray-100 text-gray-800 px-4 py-2 rounded-md shadow hover:bg-gray-200"
          >
            Download Chart
          </a>
        </div>

        {/* KPI Metrics */}
        <Metrics />

        {/* Patient Distribution & Other Charts (DO NOT REMOVE) */}
        <InteractiveCharts />

        {/* Risk Calculator */}
        <RiskCalculator />

        {/* 🚫 REMOVED FROM UI (COMMENTED FOR FUTURE USE)
        <div className="prose">
          <h3>Top Predictive Features</h3>
          <ul>
            <li>Age</li>
            <li>Serum Creatinine</li>
            <li>Ejection Fraction</li>
            <li>Platelets</li>
            <li>Serum Sodium</li>
          </ul>

          <h3>How to update</h3>
          <p>
            Run <code>colab_heart_failure_analysis.ipynb</code> in Google Colab.
            After running, download <code>outputs/summary_chart.png</code> and
            <code> outputs/insight_report.md</code> and place them in
            <code> public/assets/images/</code> (replace
            <code> summary_chart.svg</code>) and
            <code> public/insight_report.html</code> respectively.
          </p>
        </div>
        */}

        {/* Report Preview */}
        <div className="mt-8">
          <h3 className="text-lg font-medium mb-2">
            Report Preview
          </h3>

          <p className="text-sm text-gray-600 mb-3">
            Live preview of the insight report generated by the notebook.
            After you replace the static files with the notebook outputs
            this preview will show the real report.
          </p>

          <div className="w-full rounded-md overflow-hidden border">
            <iframe
              src="/insight_report.html"
              title="Insight report preview"
              style={{ width: '100%', height: 480, border: 0 }}
            />
          </div>
        </div>
      </div>
    </section>
  )
}

export default Analysis
